cs3710-001-assignment-3-Ariamestra-main/config/routes.rb
Rails.application.routes.draw do
  resources :books_libraries
  resources :books
  resources :libraries
  resources :counties
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

cs3710-001-assignment-3-Ariamestra-main/app/controllers/books_libraries_controller.rb
class BooksLibrariesController < ApplicationController
  before_action :set_books_library, only: %i[ show edit update destroy ]

  # GET /books_libraries or /books_libraries.json
  def index
    @books_libraries = BooksLibraries.all
  end

  # GET /books_libraries/1 or /books_libraries/1.json
  def show
  end

  # GET /books_libraries/new
  def new
    @books_library = BooksLibraries.new
  end

  # GET /books_libraries/1/edit
  def edit
  end

  # POST /books_libraries or /books_libraries.json
  def create
    @books_library = BooksLibraries.new(books_library_params)

    respond_to do |format|
      if @books_library.save
        format.html { redirect_to books_library_url(@books_library), notice: "Books libraries was successfully created." }
        format.json { render :show, status: :created, location: @books_library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @books_library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books_libraries/1 or /books_libraries/1.json
  def update
    respond_to do |format|
      if @books_library.update(books_library_params)
        format.html { redirect_to books_library_url(@books_library), notice: "Books libraries was successfully updated." }
        format.json { render :show, status: :ok, location: @books_library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @books_library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books_libraries/1 or /books_libraries/1.json
  def destroy
    @books_library.destroy

    respond_to do |format|
      format.html { redirect_to books_libraries_url, notice: "Books libraries was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_books_library
      @books_library = BooksLibraries.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def books_library_params
      params.require(:books_library).permit(:book_id, :library_id)
    end
end

cs3710-001-assignment-3-Ariamestra-main/app/helpers/books_libraries_helper.rb
module BooksLibrariesHelper
end

cs3710-001-assignment-3-Ariamestra-main/app/views/books_libraries/_books_libraries.html.erb
<div id="<%= dom_id books_libraries %>">
  <p>
    <strong>Book:</strong>
    <%= books_libraries.book_id %>
  </p>

  <p>
    <strong>Library:</strong>
    <%= books_libraries.library_id %>
  </p>

</div>

cs3710-001-assignment-3-Ariamestra-main/app/views/books_libraries/_form.html.erb
<%= form_with(model: books_library, url: new_books_library_path) do |form| %>
  <% if books_library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(books_library.errors.count, "error") %> prohibited this books_library from being saved:</h2>

      <ul>
        <% books_library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :library_id, style: "display: block" %>
    <%= form.text_field :library_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

cs3710-001-assignment-3-Ariamestra-main/app/views/books_libraries/edit.html.erb
<h1>Editing books libraries</h1>

<%= render "form", books_library: @books_library %>

<br>

<div>
  <%= link_to "Show this books libraries", @books_library %> |
  <%= link_to "Back to books libraries", books_libraries_path %>
</div>

cs3710-001-assignment-3-Ariamestra-main/app/views/books_libraries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books libraries</h1>

<div id="books_libraries">
  <% @books_libraries.each do |books_library| %>
    <%= render books_library %>
    <p>
      <%= link_to "Show this books libraries", books_library %>
    </p>
  <% end %>
</div>

<%= link_to "New books libraries", new_books_library_path %>

cs3710-001-assignment-3-Ariamestra-main/app/views/books_libraries/new.html.erb
<h1>New books libraries</h1>

<%= render "form", books_library: @books_library %>

<br>

<div>
  <%= link_to "Back to books libraries", books_libraries_path %>

</div>

cs3710-001-assignment-3-Ariamestra-main/app/views/books_libraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @books_library %>

<div>
  <%= link_to "Edit this books libraries", edit_books_library_path(@books_library) %> |
  <%= link_to "Back to books libraries", books_libraries_index_path %>

  <%= button_to "Destroy this books libraries", @books_library, method: :delete %>
</div>