cs3710-001-assignment-2-Ariamestra-main/config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :counties
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

cs3710-001-assignment-2-Ariamestra-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

cs3710-001-assignment-2-Ariamestra-main/app/models/county.rb
class County < ApplicationRecord
  has_many :libraries, dependent: :destroy
end

cs3710-001-assignment-2-Ariamestra-main/app/models/library.rb
class Library < ApplicationRecord
  belongs_to :county
end

cs3710-001-assignment-2-Ariamestra-main/app/models/person.rb
class Person < ApplicationRecord
end

cs3710-001-assignment-2-Ariamestra-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cs3710-001-assignment-2-Ariamestra-main/app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  before_action :set_county, only: %i[ show edit update destroy ]

  # GET /counties
  def index
    @counties = County.all
  end

  # GET /counties/1
  def show
  end

  # GET /counties/new
  def new
    @county = County.new
  end

  # GET /counties/1/edit
  def edit
  end

  # POST /counties
  def create
    @county = County.new(county_params)

    if @county.save
      redirect_to @county, notice: "County was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /counties/1
  def update
    if @county.update(county_params)
      redirect_to @county, notice: "County was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /counties/1
  def destroy
    @county.destroy
    redirect_to counties_url, notice: "County was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_county
      @county = County.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def county_params
      params.require(:county).permit(:name, :population, :coordinates)
    end
end

cs3710-001-assignment-2-Ariamestra-main/app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  before_action :set_library, only: %i[ show edit update destroy ]

  # GET /libraries
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
    @library = Library.find(params[:id])
  end

  # POST /libraries
  def create
    @library = Library.new(library_params)

    if @library.save
      redirect_to @library, notice: "Library was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /libraries/1
  def update
    if @library.update(library_params)
      redirect_to @library, notice: "Library was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /libraries/1
  def destroy
    @library.destroy
    redirect_to libraries_url, notice: "Library was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.require(:library).permit(:name, :address, :telephone, :county_id)
    end
end

cs3710-001-assignment-2-Ariamestra-main/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people
  def index
    @people = Person.all
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person, notice: "Person was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: "Person was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: "Person was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :email, :address, :phone, :library_card)
    end
end

cs3710-001-assignment-2-Ariamestra-main/app/helpers/application_helper.rb
module ApplicationHelper
end

cs3710-001-assignment-2-Ariamestra-main/app/helpers/counties_helper.rb
module CountiesHelper
end

cs3710-001-assignment-2-Ariamestra-main/app/helpers/libraries_helper.rb
module LibrariesHelper
end

cs3710-001-assignment-2-Ariamestra-main/app/helpers/people_helper.rb
module PeopleHelper
end

cs3710-001-assignment-2-Ariamestra-main/app/views/counties/_county.html.erb
<div id="<%= dom_id county %>">
  <p>
    <strong>Name:</strong>
    <%= county.name %>
  </p>

  <p>
    <strong>Population:</strong>
    <%= county.population %>
  </p>

  <p>
    <strong>Coordinates:</strong>
    <%= county.coordinates %>
  </p>

</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/counties/_form.html.erb
<%= form_with(model: county) do |form| %>
  <% if county.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
        <% county.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :population, style: "display: block" %>
    <%= form.number_field :population %>
  </div>

  <div>
    <%= form.label :coordinates, style: "display: block" %>
    <%= form.text_field :coordinates %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

cs3710-001-assignment-2-Ariamestra-main/app/views/counties/edit.html.erb
<h1>Editing county</h1>

<%= render "form", county: @county %>

<br>

<div>
  <%= link_to "Show this county", @county %> |
  <%= link_to "Back to counties", counties_path %>
</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/counties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Counties</h1>
<ul>
  <% @counties.each do |county| %>
    <li>
      <%= county.name %>
      <ul>
        <% county.libraries.each do |library| %>
          <li><%= library.name %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to "New county", new_county_path %>

cs3710-001-assignment-2-Ariamestra-main/app/views/counties/new.html.erb
<h1>New county</h1>

<%= render "form", county: @county %>

<br>

<div>
  <%= link_to "Back to counties", counties_path %>
</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/counties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @county %>

<div>
  <%= link_to "Edit this county", edit_county_path(@county) %> |
  <%= link_to "Back to counties", counties_path %>

  <%= button_to "Destroy this county", @county, method: :delete %>
</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3710Fall2023001Assignment2Ariamestra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cs3710-001-assignment-2-Ariamestra-main/app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :telephone, style: "display: block" %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :county_id %>
    <%= form.collection_select(:county_id, County.all, :id, :name) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

cs3710-001-assignment-2-Ariamestra-main/app/views/libraries/_library.html.erb
<div id="<%= dom_id library %>">
  <p>
    <strong>Name:</strong>
    <%= library.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= library.address %>
  </p>

  <p>
    <strong>Telephone:</strong>
    <%= library.telephone %>
  </p>

  <p>
    <strong>County:</strong>
    <%= library.county.name %>
  </p>

</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Show this library", @library %> |
  <%= link_to "Back to libraries", libraries_path %>
</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/libraries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libraries</h1>

<ul>
  <% @libraries.each do |library| %>
    <li>
      <%= render library %>
      <p>
        <%= link_to "Show this library", library %>
      </p>
    </li>
  <% end %>
</ul>


<%= link_to "New library", new_library_path %>

cs3710-001-assignment-2-Ariamestra-main/app/views/libraries/new.html.erb
<h1>New Library</h1>
<%= form_for @library do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :county_ids %>
    <%= f.collection_check_boxes(:county_ids, County.all, :id, :name) do |b| %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Library' %>
  </div>
<% end %>

<div>
  <%= link_to "Back to libraries", libraries_path %>
</div>

cs3710-001-assignment-2-Ariamestra-main/app/views/libraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @library %>

<div>
  <%= link_to "Edit this library", edit_library_path(@library) %> |
  <%= link_to "Back to libraries", libraries_path %>

  <%= button_to "Destroy this library", @library, method: :delete %>
</div>